apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fxqhcdf1u-dotnet-basic-gitops-repository
spec:
  url: https://github.com/testrhtaporg/fxqhcdf1u-dotnet-basic-gitops